FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода
COPY core/ ./core/
COPY server.py .

# Создание директории для БД
RUN mkdir -p /data

ENV PYTHONUNBUFFERED=1
ENV DB_PATH=/data/banhammer.db

EXPOSE 9999

CMD ["python", "server.py"]
